spring:
  #  kafka:
  #    bootstrap-servers:
  #      - broker:9092
  #        sasl:
  #          mechanism: SCRAM-SHA-512
  #          jaas:
  #            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="broker-admin" password="test123";
  #      security:
  #        protocol: SASL_SSL
  #      ssl:
  #        trust-store-location: classpath:kafka/kafka.broker.truststore.jks
  #        trust-store-password: changeit
  #        trust-store-type: JKS
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        streams:
          bindings:
            consumer-in-0:
              consumer:
                application-id: spring-kafka-stream-101
                content-type: application/*+avro
                start-offset: earliest
                key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value-serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
          binder:
            configuration:
              schema:
                registry:
                  url: http://127.0.0.1:8081
              specific:
                avro:
                  reader: true
            brokers:
              - broker:9092
      bindings:
        consumer-in-0:
          destination: ssl-topic
          consumer:
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
            default-retryable: false
            concurrency: 1
            use-native-decoding: true