spring:
  application:
    name: spring-kafka-stream
  profiles:
    active: local
management:
  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
logging:
  level:
    org.apache.kafka: WARN
    io.confluent.kafka: WARN