spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        binder:
          producer-properties:
            schema.registry.url: http://127.0.0.1:8081
            key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
          consumer-properties:
            schema.registry.url: http://127.0.0.1:8081
            key.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            specific.avro.reader: true
          transaction:
            producer:
              error-channel-enabled: true
      bindings:
        producer-out-0:
          destination: stream_topic
          content-type: application/*+avro
          binder: kafka
          producer:
            use-native-encoding: true
        consumer-in-0:
          destination: stream_topic
          group: stream-api
          content-type: application/*+avro
          binder: kafka
          producer:
            use-native-decoding: true